spring.datasource.url=jdbc:postgresql://localhost:5432/db_tg_bot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.liquibase.change-log=classpath:liquibase/scripts/changelog-master.yml
telegram.bot.token=8357488520:AAFnQoThhsqle306wy7-v5-B_rVTRqFRu4w
