spring.datasource.url=jdbc:postgresql://localhost:5432/db_tg_bot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
telegram.bot.token=!!!your token
